### PR TITLE
#1 Gateway Adjustments and Documentation

### LINKED ISSUE #1: Create and adjust API gateway
**Acceptance Criteria:**

- API gateway is operational and successfully routes requests to microservices.
- Security measures are in place and functioning as intended.
- Monitoring tools provide insights into API usage and performance.
- Documentation is complete and accessible to the development team.

### PR DESCRIPTION
**Pull request by Nazaziik**

### CODE REVIEW

**Comment by VitalikMatvieiev** [comment]
@Nazaziik The difference is only between the brunch?

**Comment by Nazaziik** [comment]
> @Nazaziik The difference is only between the brunch?

Yes

**Review by VitalikMatvieiev — APPROVED** [review]
I approved, but test if different env works good, you need to change the value for env in properties folder launchJson, and run and test with different envs

**Review by kossvat — APPROVED** [review]
Great job! i have tried my best to review this code , but i couldn't  find some issues :)

**Pull request merged**
